# Generated by Django 4.1.5 on 2023-03-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogi', '0002_postaus_luotu_pvm'),
    ]

    operations = [
        migrations.AddField(
            model_name='postaus',
            name='kuva',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
